runtime: java11
instance_class: F4
entrypoint: java -noverify -jar quasar-3.0-SNAPSHOT.jar

env_variables:
 spring_profiles_active: "dev"

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
