runtime: java11
env: flex
entrypoint: java -Xmx64m -jar com.ml.quasar-1.0-SNAPSHOT.war

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5